# Generated by Django 5.2.7 on 2025-10-25 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique vendor code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Vendor company name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Vendor address')),
                ('payment_terms', models.CharField(blank=True, help_text='Payment terms (e.g., Net 30, COD)', max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Credit limit in local currency', max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Total number of orders')),
                ('on_time_deliveries', models.PositiveIntegerField(default=0, help_text='Number of on-time deliveries')),
                ('quality_rating', models.DecimalField(decimal_places=2, default=0, help_text='Average quality rating (0-5)', max_digits=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether vendor is active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Purchase order number', max_length=20, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now, help_text='Date when PO was created')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Actual delivery date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total PO amount', max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchase.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_number', models.CharField(help_text='Goods receipt number', max_length=20, unique=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, help_text='Date of goods receipt')),
                ('total_received_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of received goods', max_digits=12)),
                ('quality_check_passed', models.BooleanField(default=True, help_text='Whether quality check passed')),
                ('quality_notes', models.TextField(blank=True, help_text='Quality inspection notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='purchase.purchaseorder')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Name of the material/item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Item description')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Ordered quantity', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity received so far', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Line Item',
                'verbose_name_plural': 'Purchase Order Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=2, help_text='Quantity received', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of receipt', max_digits=10)),
                ('quality_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending Inspection')], default='accepted', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase.goodsreceipt')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='purchase.purchaseorderlineitem')),
            ],
            options={
                'verbose_name': 'Goods Receipt Line Item',
                'verbose_name_plural': 'Goods Receipt Line Items',
                'ordering': ['created_at'],
            },
        ),
    ]
