# Generated by Django 5.2.7 on 2025-10-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('gray', 'Gray'), ('navy', 'Navy'), ('beige', 'Beige'), ('sands', 'Sands')], max_length=20),
        ),
    ]
