# Generated by Django 5.2.7 on 2025-10-25 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', help_text='BOM version', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this BOM version is active')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total material cost', max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated labor cost', max_digits=10)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, help_text='Overhead cost', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boms', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='inventory.finishedproduct')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity required per unit of finished product', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at BOM creation time', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.billofmaterials')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.rawmaterial')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
                'ordering': ['material__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Production order number', max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity to produce', max_digits=10)),
                ('planned_start_date', models.DateField(help_text='Planned production start date')),
                ('planned_end_date', models.DateField(help_text='Planned production completion date')),
                ('actual_start_date', models.DateField(blank=True, help_text='Actual production start date', null=True)),
                ('actual_end_date', models.DateField(blank=True, help_text='Actual production completion date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='inventory.finishedproduct')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-planned_start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(help_text='Work order number', max_length=20, unique=True)),
                ('stage', models.CharField(choices=[('gurat', 'Gurat (Cutting)'), ('assembly', 'Assembly'), ('press', 'Press'), ('finishing', 'Finishing')], help_text='Production stage', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity for this work order', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('planned_start_date', models.DateField(help_text='Planned start date for this stage')),
                ('planned_end_date', models.DateField(help_text='Planned completion date for this stage')),
                ('actual_start_date', models.DateField(blank=True, help_text='Actual start date', null=True)),
                ('actual_end_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Work instructions and notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='manufacturing.productionorder')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['production_order', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='ProductionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, help_text='Progress percentage (0-100)', max_digits=5)),
                ('quantity_completed', models.DecimalField(decimal_places=2, help_text='Quantity completed', max_digits=10)),
                ('progress_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of progress update')),
                ('notes', models.TextField(blank=True, help_text='Progress notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='manufacturing.workorder')),
            ],
            options={
                'verbose_name': 'Production Progress',
                'verbose_name_plural': 'Production Progress',
                'ordering': ['-progress_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, help_text='Planned quantity to consume', max_digits=10)),
                ('actual_quantity', models.DecimalField(decimal_places=2, help_text='Actual quantity consumed', max_digits=10)),
                ('consumption_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of consumption')),
                ('notes', models.TextField(blank=True, help_text='Consumption notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.rawmaterial')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='manufacturing.workorder')),
            ],
            options={
                'verbose_name': 'Material Consumption',
                'verbose_name_plural': 'Material Consumptions',
                'ordering': ['-consumption_date'],
            },
        ),
    ]
