# Generated by Django 5.2.7 on 2025-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='allocated_stages',
            field=models.JSONField(default=list, help_text='List of production stages that use this material'),
        ),
    ]
