# Generated by Django 5.2.7 on 2025-10-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_bomitem_allocated_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='BOM Cost (auto-calculated)', max_digits=10),
        ),
    ]
